services:
  openvpn-client:
    build:
      context: ./build
      dockerfile: ./build/Dockerfile
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    environment:
      - KILL_SWITCH=off
#      - CONFIG_FILE=dk-cph.ovpn
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./confs:/config
    ports:
      - 11944:1194
#    restart: unless-stopped
