services:
  openvpn-client:
    build:
      context: ./build
      dockerfile: Dockerfile
    # container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    environment:
      - KILL_SWITCH=off
      - CONFIG_FILE=dk-cph.ovpn
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./confs:/config
    ports:
      - 11944:1194
    networks:
      - openvpnclient
#    restart: unless-stopped
  socks5:
    # restart: always
    image: serjs/go-socks5-proxy
    environment:
      - PROXY_PORT=1080
    ports:
      - "1080:1080"
    networks:
      - openvpnclient

networks:
  - openvpnclient
